In [23]:
import pandas as pd
import numpy as np

In [24]:
sheets=['T6 Wine production','T8 Wine prodn per capita','T10 Wine export vol','T15 Wine import vol',\
       'T34 Wine consumption vol','T38 Wine consumption per capita','T58 Population']
dfs=[];
for i in range(0,len(sheets)):
    dfs.append('df'+str(i));

In [25]:
countries=list(pd.read_excel('Wine_History.xlsx', sheet_name=sheets[0], header=0, index_col=None).columns.values)[1:]
years=range(1865,2016)

In [12]:
countries

['France',
 'Italy',
 'Portugal',
 'Spain',
 'Austria',
 'Norway',
 'Belgium',
 'Denmark',
 'Finland',
 'Germany',
 'Greece',
 'Ireland',
 'Netherlands',
 'Sweden',
 'Switzerland',
 'United Kingdom',
 'Other WEM',
 'Bulgaria',
 'Croatia',
 'Georgia',
 'Hungary',
 'Moldova',
 'Romania',
 'Russia',
 'Ukraine',
 'Other ECA',
 'Australia',
 'New Zealand',
 'Canada',
 'United States',
 'Argentina',
 'Brazil',
 'Chile',
 'Mexico',
 'Uruguay',
 'Other LAC',
 'Algeria',
 'Morocco',
 'South Africa',
 'Tunisia',
 'Turkey',
 'Other AME',
 'China',
 'Hong Kong',
 'India',
 'Japan',
 'Korea',
 'Malaysia',
 'Philippines',
 'Singapore',
 'Taiwan',
 'Thailand',
 'World',
 'Unnamed: 54']

In [26]:
for i,sheet in enumerate(sheets):
    dfs[i]=pd.read_excel('Wine_History.xlsx', sheet_name=sheet, header=0, index_col=None)

In [28]:
dfs[0].shape

(152, 54)

In [71]:
df=pd.DataFrame({},columns=years)
for i,country in enumerate(countries):
    row=[]
    for j,year in enumerate(years):
        cell={"country":country,
              "year": year,
              "Production": dfs[0].iloc[j,i+1],
              "Production_capita":dfs[1].iloc[j,i+1],
              "Export":dfs[2].iloc[j,i+1],
              "Import":dfs[3].iloc[j,i+1],
              "Consumption":dfs[4].iloc[j,i+1],
              "Consumption_capita":dfs[5].iloc[j,i+1],
              "Population":dfs[6].iloc[j,i+1]
             }  
        row.append(cell)
    df=df.append(pd.Series(row, index = df.columns),ignore_index=True)

In [72]:
df.head()

,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,"{'country': 'France', 'year': 1865, 'Productio...","{'country': 'France', 'year': 1866, 'Productio...","{'country': 'France', 'year': 1867, 'Productio...","{'country': 'France', 'year': 1868, 'Productio...","{'country': 'France', 'year': 1869, 'Productio...","{'country': 'France', 'year': 1870, 'Productio...","{'country': 'France', 'year': 1871, 'Productio...","{'country': 'France', 'year': 1872, 'Productio...","{'country': 'France', 'year': 1873, 'Productio...","{'country': 'France', 'year': 1874, 'Productio...",...,"{'country': 'France', 'year': 2006, 'Productio...","{'country': 'France', 'year': 2007, 'Productio...","{'country': 'France', 'year': 2008, 'Productio...","{'country': 'France', 'year': 2009, 'Productio...","{'country': 'France', 'year': 2010, 'Productio...","{'country': 'France', 'year': 2011, 'Productio...","{'country': 'France', 'year': 2012, 'Productio...","{'country': 'France', 'year': 2013, 'Productio...","{'country': 'France', 'year': 2014, 'Productio...","{'country': 'France', 'year': 2015, 'Productio..."
1,"{'country': 'Italy', 'year': 1865, 'Production...","{'country': 'Italy', 'year': 1866, 'Production...","{'country': 'Italy', 'year': 1867, 'Production...","{'country': 'Italy', 'year': 1868, 'Production...","{'country': 'Italy', 'year': 1869, 'Production...","{'country': 'Italy', 'year': 1870, 'Production...","{'country': 'Italy', 'year': 1871, 'Production...","{'country': 'Italy', 'year': 1872, 'Production...","{'country': 'Italy', 'year': 1873, 'Production...","{'country': 'Italy', 'year': 1874, 'Production...",...,"{'country': 'Italy', 'year': 2006, 'Production...","{'country': 'Italy', 'year': 2007, 'Production...","{'country': 'Italy', 'year': 2008, 'Production...","{'country': 'Italy', 'year': 2009, 'Production...","{'country': 'Italy', 'year': 2010, 'Production...","{'country': 'Italy', 'year': 2011, 'Production...","{'country': 'Italy', 'year': 2012, 'Production...","{'country': 'Italy', 'year': 2013, 'Production...","{'country': 'Italy', 'year': 2014, 'Production...","{'country': 'Italy', 'year': 2015, 'Production..."
2,"{'country': 'Portugal', 'year': 1865, 'Product...","{'country': 'Portugal', 'year': 1866, 'Product...","{'country': 'Portugal', 'year': 1867, 'Product...","{'country': 'Portugal', 'year': 1868, 'Product...","{'country': 'Portugal', 'year': 1869, 'Product...","{'country': 'Portugal', 'year': 1870, 'Product...","{'country': 'Portugal', 'year': 1871, 'Product...","{'country': 'Portugal', 'year': 1872, 'Product...","{'country': 'Portugal', 'year': 1873, 'Product...","{'country': 'Portugal', 'year': 1874, 'Product...",...,"{'country': 'Portugal', 'year': 2006, 'Product...","{'country': 'Portugal', 'year': 2007, 'Product...","{'country': 'Portugal', 'year': 2008, 'Product...","{'country': 'Portugal', 'year': 2009, 'Product...","{'country': 'Portugal', 'year': 2010, 'Product...","{'country': 'Portugal', 'year': 2011, 'Product...","{'country': 'Portugal', 'year': 2012, 'Product...","{'country': 'Portugal', 'year': 2013, 'Product...","{'country': 'Portugal', 'year': 2014, 'Product...","{'country': 'Portugal', 'year': 2015, 'Product..."
3,"{'country': 'Spain', 'year': 1865, 'Production...","{'country': 'Spain', 'year': 1866, 'Production...","{'country': 'Spain', 'year': 1867, 'Production...","{'country': 'Spain', 'year': 1868, 'Production...","{'country': 'Spain', 'year': 1869, 'Production...","{'country': 'Spain', 'year': 1870, 'Production...","{'country': 'Spain', 'year': 1871, 'Production...","{'country': 'Spain', 'year': 1872, 'Production...","{'country': 'Spain', 'year': 1873, 'Production...","{'country': 'Spain', 'year': 1874, 'Production...",...,"{'country': 'Spain', 'year': 2006, 'Production...","{'country': 'Spain', 'year': 2007, 'Production...","{'country': 'Spain', 'year': 2008, 'Production...","{'country': 'Spain', 'year': 2009, 'Production...","{'country': 'Spain', 'year': 2010, 'Production...","{'country': 'Spain', 'year': 2011, 'Production...","{'country': 'Spain', 'year': 2012, 'Production...","{'country': 'Spain', 'year': 2013, 'Production...","{'country': 'Spain', 'year': 2014, 'Production...","{'country': 'Spain', 'year': 2015, 'Production..."
4,"{'country': 'Austria', 'year': 1865, 'Producti...","{'country': 'Austria', 'year': 1866, 'Producti...","{'country': 'Austria', 'year': 1867, 'Producti...","{'country': 'Austria', 'year': 1868, 'Producti...","{'country': 'Austria', 'year': 1869, 'Producti...","{'country': 'Austria', 'year': 1870, 'Producti...","{'country': 'Austria', 'year': 1871, 'Producti...","{'country': 'Austria', 'year': 1872, 'Producti...","{'country': 'Austria', 'year': 1873, 'Producti...","{'country': 'Austria', 'year': 1874, 'Producti...",...,"{'country': 'Austria', 'year': 2006, 'Producti...","{'country': 'Austria', 'year': 2007, 'Producti...","{'country': 'Austria', 'year': 2008, 'Producti...","{'country': 'Austria', 'year': 2009, 'Producti...","{'country': 'Austria', 'year': 2010, 'Producti...","{'country': 'Austria', 'year': 2011, 'Producti...","{'country': 'Austria', 'year': 2012, 'Producti...","{'country': 'Austria', 'year': 2013, 'Producti...","{'country': 'Austria', 'year': 2014, 'Producti...","{'country': 'Austria', 'year': 2015, 'Producti..."

In [73]:
df.to_json('sqldb.json',orient="split",index=False)